import time

from selenium import webdriver
opts = webdriver.ChromeOptions()
opts.add_experimental_option("detach", True)
driver = webdriver.Chrome(opts)
driver.get('https://www.saucedemo.com/')
time.sleep(2)
driver.maximize_window()
driver.find_element('id', 'user-name').send_keys('problem_user')
time.sleep(1)
driver.find_element('id', 'password').send_keys('secret_sauce')
time.sleep(1)
driver.find_element('id', 'login-button').click()
time.sleep(3)
driver.find_element('id', 'react-burger-menu-btn').click()
time.sleep(2)
driver.find_element('id', 'logout_sidebar_link').click()

from selenium import webdriver
opts = webdriver.ChromeOptions()
opts.add_experimental_option("detach", True)
driver = webdriver.Chrome(opts)
driver.get('https://testautomationpractice.blogspot.com/')
time.sleep(2)
driver.maximize_window()
driver.find_element('id','name').send_keys('Abhishek Upadhye')
time.sleep(1)
driver.find_element('id','email').send_keys('abhishekupadhye@gmail.com')
time.sleep(1)
driver.find_element('id','phone').send_keys('7204071689')
time.sleep(1)
driver.find_element('id','textarea').send_keys('Belagavi')
time.sleep(1)
driver.find_element('id','male').click()
time.sleep(1)
driver.find_element('id','wednesday').click()
time.sleep(1)

from selenium import webdriver
opts = webdriver.ChromeOptions()
opts.add_experimental_option("detach", True)
driver = webdriver.Chrome(opts)
driver.get("https://www.facebook.com/")
time.sleep(2)
driver.maximize_window()
driver.find_element('id','email').send_keys('7204071688')
time.sleep(1)
driver.find_element('id','pass').send_keys('Upadhye@1998')
time.sleep(1)
driver.find_element('name','login').click()
time.sleep(5)
